name: ci

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: docker build --rm=false -t ghcr.io/${{github.actor}}/node-express:prod .

      - name: Docker push
        run: docker push ghcr.io/${{github.actor}}/node-express:prod

      - name: Deploy on Section
        env:
          KEI_URL: "${{ secrets.KEI_URL }}"
          SECTION_API_TOKEN: "${{ secrets.SECTION_API_TOKEN }}"
          DEBUG: 1
        run: | 
          ./ci/deploy.sh main